services:

  back:
    container_name: Back_API_Bin
    build: .
    restart: always
    tty: true
    ports:
      - 8000:8000

  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083                 
      - 8085:8081
